server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-server

  ### amqp
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
              - http://127.0.0.1:3000
              - http://192.168.0.2:3000
              - http://192.168.0.5:3000
            allow-credentials: true
            allowedHeaders:
              - authorization
              - content-type
              - credential
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-resource-service # NOTE : OAUTH 요청
          uri: lb://auth-resource-service
          predicates:
            - Path=/auth-resource-service/**
          filters:
            - RewritePath=/auth-resource-service/(?<path>.*), /$\{path}

        - id: user-service # NOTE : silent-refresh
          uri: lb://user-service
          predicates:
            - Path=/user-service/auth/silent-refresh
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}

        - id: user-service # NOTE : 그 외 모든 User-Service 요청 ( login, register 는 게이트웨이 안거침 )
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
            - name: AuthorizationFilter

        - id: student-service # NOTE : 그 외 모든 User-Service 요청 ( login, register 는 게이트웨이 안거침 )
          uri: lb://student-service
          predicates:
            - Path=/student-service/**
          filters:
            - RewritePath=/student-service/(?<path>.*), /$\{path}
